---
- name: Restart taskflow-api
  ansible.builtin.systemd:
    name: taskflow-api
    state: restarted
    daemon_reload: true

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
