---
galaxy_info:
  role_name: node_exporter
  author: ForEach Academy
  description: Installe node_exporter (Prometheus) en service systemd
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
dependencies: []
